### ISSUE TITLE
Average time to align monolingual word embeddings: the supervised way?

### ISSUE THREAD

**Issue by gvishal** [facebookresearch/MUSE#7] opened 2017-12-27 15:46 UTC
I am aligning english and hindi fasttext monolingual embeddings using the the supervised way on a GPU. Are there are time estimates as to how long it takes? It's been 4 hours, and it is still in the first refinement step.

I ran the following command:
```
python supervised.py --src_lang en --tgt_lang hi --src_emb wiki.en.vec --tgt_emb wiki.hi.vec --n_iter 5 --dico_train default
```
Update: it was running for close to 20 hours on a GeForce GTX 1080, constantly hogging 1 CPU core, but no entries were added to the log. I am running it again.

Log:
```
INFO - 12/27/17 17:57:14 - 0:00:00 - ============ Initialized logger ============
INFO - 12/27/17 17:57:14 - 0:00:00 - cuda: True
                                     dico_build: S2T&T2S
                                     dico_max_rank: 10000
                                     dico_max_size: 0
                                     dico_method: csls_knn_10
                                     dico_min_size: 0
                                     dico_threshold: 0
                                     dico_train: default
                                     emb_dim: 300
                                     exp_path: /MUSE/dumped/hidden
                                     export: True
                                     max_vocab: 200000
                                     n_iters: 5
                                     normalize_embeddings: 
                                     seed: -1
                                     src_emb:wiki.en.vec
                                     src_lang: en
                                     tgt_emb: wiki.hi.vec
                                     tgt_lang: hi
                                     verbose: 2
INFO - 12/27/17 17:57:14 - 0:00:00 - The experiment will be stored in hidden/MUSE/dumped/hidden
INFO - 12/27/17 17:57:25 - 0:00:11 - Loaded 200000 pre-trained word embeddings
INFO - 12/27/17 17:57:45 - 0:00:31 - Loaded 158016 pre-trained word embeddings
INFO - 12/27/17 17:57:49 - 0:00:34 - Found 8704 pairs of words in the dictionary (4998 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/27/17 17:57:49 - 0:00:34 - Starting refinement iteration 0...
INFO - 12/27/17 17:57:49 - 0:00:35 - ====================================================================
INFO - 12/27/17 17:57:49 - 0:00:35 -                        Dataset      Found     Not found          Rho
INFO - 12/27/17 17:57:49 - 0:00:35 - ====================================================================
INFO - 12/27/17 17:57:49 - 0:00:35 -                   EN_MTurk-771        771             0       0.6689
INFO - 12/27/17 17:57:49 - 0:00:35 -                   EN_MTurk-287        286             1       0.6773
INFO - 12/27/17 17:57:49 - 0:00:35 -                  EN_SIMLEX-999        998             1       0.3823
INFO - 12/27/17 17:57:49 - 0:00:35 -                  EN_WS-353-REL        252             0       0.6820
INFO - 12/27/17 17:57:49 - 0:00:35 -                 EN_RW-STANFORD       1323           711       0.5080
INFO - 12/27/17 17:57:49 - 0:00:35 -                       EN_MC-30         30             0       0.8123
INFO - 12/27/17 17:57:49 - 0:00:35 -                  EN_WS-353-ALL        353             0       0.7388
INFO - 12/27/17 17:57:49 - 0:00:35 -                    EN_VERB-143        144             0       0.3973
INFO - 12/27/17 17:57:49 - 0:00:35 -                   EN_MEN-TR-3k       3000             0       0.7637
INFO - 12/27/17 17:57:49 - 0:00:35 -                      EN_YP-130        130             0       0.5333
INFO - 12/27/17 17:57:49 - 0:00:35 -                       EN_RG-65         65             0       0.7974
INFO - 12/27/17 17:57:49 - 0:00:35 -                   EN_SEMEVAL17        379             9       0.7216
INFO - 12/27/17 17:57:49 - 0:00:35 -                  EN_WS-353-SIM        203             0       0.7811
INFO - 12/27/17 17:57:49 - 0:00:35 - ====================================================================
INFO - 12/27/17 17:57:49 - 0:00:35 - Monolingual source word similarity score average: 0.65108
INFO - 12/27/17 17:57:49 - 0:00:35 - Found 2032 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/27/17 17:57:50 - 0:00:36 - 1500 source words - nn - Precision at k = 1: 23.800000
INFO - 12/27/17 17:57:51 - 0:00:36 - 1500 source words - nn - Precision at k = 5: 41.133333
INFO - 12/27/17 17:57:51 - 0:00:37 - 1500 source words - nn - Precision at k = 10: 48.133333
INFO - 12/27/17 17:57:51 - 0:00:37 - Found 2032 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)

```

**Comment by aconneau** [comment] 2017-12-27 15:53
It's hard to give an average time since it depends on your hardware. If you are on CPU and haven't installed FAISS, please consider installing FAISS-CPU as it will speed up the computation of the knn graph. The bottleneck is the computation of the synthetic dictionary via CSLS.

**Comment by glample** [comment] 2017-12-28 00:09
4 hours seems abnormally long, there might be something wrong. What command did you use exactly?

**Comment by gvishal** [comment] 2017-12-28 09:56
```python supervised.py --src_lang en --tgt_lang hi --src_emb /home/jaspreet/vg/datasets/embeddings/wiki.en.vec --tgt_emb /home/jaspreet/vg/datasets/embeddings/wiki.hi.vec --n_iter 5 --dico_train default```

*Updated top-level description/comment.

**Comment by glample** [comment] 2017-12-28 10:15
Hi @gvishal, this is what I get on my machine using your command:

```
............
............
INFO - 12/28/17 02:11:23 - 0:00:45 - Monolingual source word similarity score average: 0.65108
INFO - 12/28/17 02:11:23 - 0:00:45 - Found 2032 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/28/17 02:11:23 - 0:00:45 - 1500 source words - nn - Precision at k = 1: 23.800000
INFO - 12/28/17 02:11:23 - 0:00:45 - 1500 source words - nn - Precision at k = 5: 41.133333
INFO - 12/28/17 02:11:23 - 0:00:45 - 1500 source words - nn - Precision at k = 10: 48.133333
INFO - 12/28/17 02:11:23 - 0:00:45 - Found 2032 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/28/17 02:11:38 - 0:01:00 - 1500 source words - csls_knn_10 - Precision at k = 1: 33.333333
INFO - 12/28/17 02:11:39 - 0:01:00 - 1500 source words - csls_knn_10 - Precision at k = 5: 51.200000
INFO - 12/28/17 02:11:39 - 0:01:00 - 1500 source words - csls_knn_10 - Precision at k = 10: 58.133333
INFO - 12/28/17 02:11:42 - 0:01:04 - Building the train dictionary ...
INFO - 12/28/17 02:11:42 - 0:01:04 - New train dictionary of 4117 pairs.
INFO - 12/28/17 02:11:42 - 0:01:04 - Mean cosine (nn method, S2T build, 10000 max size): 0.62036
INFO - 12/28/17 02:12:19 - 0:01:40 - Building the train dictionary ...
INFO - 12/28/17 02:12:19 - 0:01:40 - New train dictionary of 4424 pairs.
INFO - 12/28/17 02:12:19 - 0:01:40 - Mean cosine (csls_knn_10 method, S2T build, 10000 max size): 0.61113
............
............
INFO - 12/28/17 02:12:19 - 0:01:40 - * Saving the mapping to /private/home/guismay/code/MUSE/dumped/ajsd040n1x/best_mapping.t7 ...
INFO - 12/28/17 02:12:19 - 0:01:40 - End of refinement iteration 0.


INFO - 12/28/17 02:12:19 - 0:01:40 - Starting refinement iteration 1...
```

This is using a P100 GPU, but without FAISS. Are you sure you are using the GPU?

**Comment by gvishal** [comment] 2017-12-28 10:22
The process is consuming memory on the gpu, but it is consuming 0% GPU cycles. I'll debug why this is happening. TF works fine, I have CUDA 8 and python 3.5.

**Comment by gvishal** [comment] 2017-12-28 10:24
Additionally, the process does not respond to Ctrl-C, I have to kill it using other means!

**Comment by glample** [comment] 2017-12-28 11:26
The problem should be there in `get_word_translation_accuracy`:
https://github.com/facebookresearch/MUSE/blob/master/src/evaluation/word_translation.py#L115-L129

I guess the problem comes from the `get_nn_avg_dist` call. Can you try to add a print before / after line 121 or something, to see if this is really the slow part?

**Comment by gvishal** [comment] 2017-12-28 12:33
Here's the log, I added a bunch of more debug statements.

Yes, that looks like the issue. There's been no update in 40 mins after that.

```
INFO - 12/28/17 17:19:58 - 0:00:11 - Loaded 200000 pre-trained word embeddings
INFO - 12/28/17 17:20:16 - 0:00:28 - Loaded 158016 pre-trained word embeddings
INFO - 12/28/17 17:20:19 - 0:00:32 - Found 8704 pairs of words in the dictionary (4998 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/28/17 17:20:19 - 0:00:32 - Starting refinement iteration 0...
INFO - 12/28/17 17:20:20 - 0:00:32 - ====================================================================
INFO - 12/28/17 17:20:20 - 0:00:32 -                        Dataset      Found     Not found          Rho
INFO - 12/28/17 17:20:20 - 0:00:32 - ====================================================================
INFO - 12/28/17 17:20:20 - 0:00:32 -                   EN_MTurk-771        771             0       0.6689
INFO - 12/28/17 17:20:20 - 0:00:32 -                   EN_MTurk-287        286             1       0.6773
INFO - 12/28/17 17:20:20 - 0:00:32 -                  EN_SIMLEX-999        998             1       0.3823
INFO - 12/28/17 17:20:20 - 0:00:32 -                  EN_WS-353-REL        252             0       0.6820
INFO - 12/28/17 17:20:20 - 0:00:32 -                 EN_RW-STANFORD       1323           711       0.5080
INFO - 12/28/17 17:20:20 - 0:00:32 -                       EN_MC-30         30             0       0.8123
INFO - 12/28/17 17:20:20 - 0:00:32 -                  EN_WS-353-ALL        353             0       0.7388
INFO - 12/28/17 17:20:20 - 0:00:32 -                    EN_VERB-143        144             0       0.3973
INFO - 12/28/17 17:20:20 - 0:00:32 -                   EN_MEN-TR-3k       3000             0       0.7637
INFO - 12/28/17 17:20:20 - 0:00:32 -                      EN_YP-130        130             0       0.5333
INFO - 12/28/17 17:20:20 - 0:00:32 -                       EN_RG-65         65             0       0.7974
INFO - 12/28/17 17:20:20 - 0:00:32 -                   EN_SEMEVAL17        379             9       0.7216
INFO - 12/28/17 17:20:20 - 0:00:32 -                  EN_WS-353-SIM        203             0       0.7811
INFO - 12/28/17 17:20:20 - 0:00:32 - ====================================================================
INFO - 12/28/17 17:20:20 - 0:00:32 - Monolingual source word similarity score average: 0.65108
INFO - 12/28/17 17:20:20 - 0:00:32 - Found 2032 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/28/17 17:20:20 - 0:00:32 - 1500 source words - nn - Precision at k = 1: 23.800000
INFO - 12/28/17 17:20:20 - 0:00:33 - 1500 source words - nn - Precision at k = 5: 41.133333
INFO - 12/28/17 17:20:20 - 0:00:33 - 1500 source words - nn - Precision at k = 10: 48.133333
INFO - 12/28/17 17:20:20 - 0:00:33 - Found 2032 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 12/28/17 17:20:20 - 0:00:33 - get_nn_avg_dist started.
INFO - 12/28/17 17:20:20 - 0:00:33 - Faiss available.
INFO - 12/28/17 17:20:20 - 0:00:33 - GPU available.
INFO - 12/28/17 17:20:20 - 0:00:33 - before faiss.GpuIndexFlatIP(res, emb.shape[1], config)
```

**Comment by glample** [comment] 2017-12-28 12:50
Interesting. The line `faiss.GpuIndexFlatIP(res, emb.shape[1], config)` is not supposed to run anything, this is just some initialization. Maybe the issue is coming from FAISS.

Can you try here:
https://github.com/facebookresearch/MUSE/blob/master/src/utils.py#L151
to replace `if FAISS_AVAILABLE:` by `if False` and see if this works?

**Comment by gvishal** [comment] 2017-12-28 13:42
Disabling FAISS doesn't to be working. I instead ran FAISS in CPU mode and it is working! Much faster than GPU, I'd say :P

**Comment by glample** [comment] 2017-12-28 17:21
What happens when you disable FAISS? What line is blocking in that case? This should be easier to debug.

**Comment by gvishal** [comment] 2017-12-28 19:59
Okay, I'll try that. I think the issue is with pytorch getting stuck somewhere.

**Comment by glample** [comment] 2018-01-02 09:44
I'm closing the issue since you got it working with FAISS-CPU. Feel free to re-open if you have more issues.

**Closed by glample** 2018-01-02 09:44 UTC
