### ISSUE TITLE
where I tried the supervised.py, I got "ValueError: The input must have at least 3 entries!"

### ISSUE THREAD

**Issue by miscy210** [facebookresearch/MUSE#10] opened 2018-01-06 12:33 UTC
#### But when I tried the following command to test the supervised method:

python3 supervised.py --src_lang en --tgt_lang es --src_emb ../wiki.en.vec --tgt_emb ../Spanish_wiki.es.vec --n_iter 5 --dico_train identical_char --cuda False

#### Here is the logs:

Failed to load GPU Faiss: No module named 'swigfaiss_gpu'
Faiss falling back to CPU-only.
Impossible to import Faiss-GPU. Switching to FAISS-CPU, this will be slower.

INFO - 01/06/18 12:20:38 - 0:00:00 - ============ Initialized logger ============
INFO - 01/06/18 12:20:38 - 0:00:00 - cuda: False
                                     dico_build: S2T&T2S
                                     dico_max_rank: 10000
                                     dico_max_size: 0
                                     dico_method: csls_knn_10
                                     dico_min_size: 0
                                     dico_threshold: 0
                                     dico_train: identical_char
                                     emb_dim: 300
                                     exp_path: /Documents/MUSE-master/dumped/nrthsd26ay
                                     export: True
                                     max_vocab: 200000
                                     n_iters: 5
                                     normalize_embeddings: 
                                     seed: -1
                                     src_emb: ../wiki.en.vec
                                     src_lang: en
                                     tgt_emb: ../Spanish_wiki.es.vec
                                     tgt_lang: es
                                     verbose: 2
INFO - 01/06/18 12:20:38 - 0:00:00 - The experiment will be stored in /Documents/MUSE-master/dumped/nrthsd26ay
INFO - 01/06/18 12:20:48 - 0:00:10 - Loaded 200000 pre-trained word embeddings
INFO - 01/06/18 12:21:02 - 0:00:24 - Loaded 200000 pre-trained word embeddings
INFO - 01/06/18 12:21:04 - 0:00:26 - Found 85912 pairs of identical character strings.
INFO - 01/06/18 12:21:05 - 0:00:26 - Starting refinement iteration 0...
INFO - 01/06/18 12:22:14 - 0:01:36 - ====================================================================
INFO - 01/06/18 12:22:14 - 0:01:36 -                        Dataset      Found     Not found          Rho
INFO - 01/06/18 12:22:14 - 0:01:36 - ====================================================================
here:
n--> 771
m--> 771
Traceback (most recent call last):
  File "supervised.py", line 92, in <module>
    evaluator.all_eval(to_log)
  File "/Documents/MUSE-master/src/evaluation/evaluator.py", line 188, in all_eval
    self.monolingual_wordsim(to_log)
  File "/Documents/MUSE-master/src/evaluation/evaluator.py", line 43, in monolingual_wordsim
    self.mapping(self.src_emb.weight).data.cpu().numpy()
  File "/Documents/MUSE-master/src/evaluation/wordsim.py", line 104, in get_wordsim_scores
    coeff, found, not_found = get_spearman_rho(word2id, embeddings, filepath, lower)
  File "/Documents/MUSE-master/src/evaluation/wordsim.py", line 83, in get_spearman_rho
    return spearmanr(gold, pred).correlation, len(gold), not_found
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/scipy/stats/stats.py", line 3301, in spearmanr
    rho, pval = mstats_basic.spearmanr(a, b, axis)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/scipy/stats/mstats_basic.py", line 461, in spearmanr
    raise ValueError("The input must have at least 3 entries!")
ValueError: The input must have at least 3 entries!

**Comment by glample** [comment] 2018-01-06 12:49
Hello,

Did you run the `get_evaluation.sh` script inside the `data` folder?

**Comment by miscy210** [comment] 2018-01-06 13:12
@glample Thank you. 
And yes, this script is to download all the corpus, wordvec models and dictionaries. You mean the problem maybe in these data?

**Comment by glample** [comment] 2018-01-06 13:25
I'm not sure what the problem is, and I was wondering whether the evaluation files were properly downloaded.

Can you comment out this line: https://github.com/facebookresearch/MUSE/blob/master/src/evaluation/evaluator.py#L188 and see what happens?

**Comment by miscy210** [comment] 2018-01-06 13:40
It seems worked.
here is the log message for now
[logs.txt](https://github.com/facebookresearch/MUSE/files/1608807/logs.txt)

I wonder why?

**Comment by glample** [comment] 2018-01-06 14:06
I'm not sure this is working. The translation accuracy is 0%. What are the embeddings you are using?

**Comment by glample** [comment] 2018-01-06 15:10
Can you try to re-download the Spanish embeddings using this command?

curl -Lo data/wiki.es.vec https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.es.vec

And see if this helps?

**Comment by miscy210** [comment] 2018-01-07 02:14
@glample sorry to trouble so much.
 I think the problem is in the environment. Yestoday, I reinstall the environment with [the pytorch/pytorch docker image](https://hub.docker.com/r/pytorch/pytorch/) which used the python3.5. Since there says pytorch's system requirement is python3.5 or python2.7, and my former py is python3.6.
Thank you very much. ^^.

**Comment by glample** [comment] 2018-01-07 14:19
Not sure I get it. Did you manage to fix the problem?

**Comment by miscy210** [comment] 2018-01-07 14:30
The problem is solved for now.
I just re-built the docker image with [pytorch](https://hub.docker.com/r/pytorch/pytorch/). Then everything goes fine. And the difference between the two images is the python version. So I think the problem may be the adaption of pytorch with python3.6.

**Comment by glample** [comment] 2018-01-07 15:24
Sounds good, thank you. I'll close the issue then

**Closed by glample** 2018-01-07 15:24 UTC
